version: '3.7'
services:
  php:
    build: ./docker/php
    volumes:
      - ./symfony/:/app
    working_dir: /app
    networks:
      - main
  web:
    image: nginx:alpine
    volumes:
      - ./symfony/public:/app/public
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - main
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test1
      POSTGRES_DB: redsms
    volumes:
      - redsms:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - main
networks:
  main:

volumes:
  redsms:
